on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: action-merge-translations

jobs:
  action-merge-translations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install gettext
      run: sudo apt-get install gettext

    - name: Branch
      run: |
        git checkout -b action-merge-translations

    - name: Merge translations
      run: python ./kpac i18n
    
    - name: Check if there are changes
      id: check_changes
      run: |
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes detected."
          echo "is_changed=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected."
          echo "is_changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.check_changes.outputs.is_changed == 'true'
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Merge translations"
        git push origin action-merge-translations -f

    - name: Create Pull Request
      if: steps.check_changes.outputs.is_changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr edit ${{ env.BRANCH_NAME }} -b '${{ env.PR_BODY }}' -t '${{ env.PR_TITLE }}'  && gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create --fill -B main -H ${{ env.BRANCH_NAME }} --title "Merge translations" --body "This PR was created by GitHub Actions"
